# GitHub Release configuration
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - github-actions
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔒 Security
      labels:
        - security
        - vulnerability
    - title: ⚡ Performance
      labels:
        - performance
        - optimization
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
        - refactor
    - title: 📦 Dependencies
      labels:
        - dependencies
        - npm
        - github-actions
    - title: 🧪 Testing
      labels:
        - test
        - testing
    - title: Other Changes
      labels:
        - "*"